pinned_apps:
#  - 'sys/*'
  - sys/files
  - sys/myjobs
  - sys/activejobs
  - sys/shell

  - sys/bc_codeserver
  - sys/bc_jupyter
#  - sys/bc_k8s_jupyter
#  - sys/bc_rstudio
  - sys/bc_orange
  - sys/bc_ijulia

#pinned_apps_menu_length: 6
#pinned_apps_group_by: 'category'

dashboard_layout:
  rows:
  - columns:
    - width: 12
      widgets:
      - wellcome
  - columns:
    - width: 8
      widgets:
      - pinned_apps
      - motd
    - width: 4
      widgets:
#      - xdmod_widget_job_efficiency
      - xdmod_widget_jobs
