FROM python:3.11-slim
MAINTAINER Leonardo Loures <luvres@hotmail.com>

RUN \
  pip --no-cache-dir install --upgrade pip \
  \
  && pip --no-cache-dir install \
       notebook \
       matplotlib \
       dask \
       pandas \
       numpy \
       scikit-learn \
       nbconvert \
       pandoc
