pinned_apps:
#  - 'sys/*'
  - sys/files
  - sys/shell
  - sys/myjobs
  - sys/activejobs

#  - sys/bc_codeserver
#  - sys/bc_jupyter
#  - sys/bc_rstudio

#pinned_apps_menu_length: 6
#pinned_apps_group_by: 'category'

dashboard_layout:
  rows:
  - columns:
    - width: 12
      widgets:
      - wellcome
  - columns:
    - width: 4
      widgets:
      - motd
    - width: 8
      widgets:
      - pinned_apps

#dashboard_layout:
#  rows:
#  - columns:
#    - width: 8
#      widgets:
#      - pinned_apps
#      - motd
#    - width: 4
#      widgets:
#      - xdmod_widget_job_efficiency
#      - xdmod_widget_jobs
