pinned_apps:
#  - 'sys/*'
  - sys/files
  - sys/shell
  - sys/myjobs
  - sys/activejobs

  - sys/bc_jupyter
  - sys/bc_rstudio
  - sys/bc_codeserver

#pinned_apps_menu_length: 6
#pinned_apps_group_by: 'category'
