---
name: Code Server
category: Interactive Apps
subcategory: Servers
role: batch_connect
description: |
  This app will launch a [VS Code] server using [Code Server] on the [HPCC cluster].
tile:
  title: "Code Server"
  border_color: "gray"
