FROM izone/hpc:r8ww-slurm
MAINTAINER Leonardo Loures <luvres@hotmail.com>

ARG UID_SASLAUNTH=987 \
    UID_ONDEMAND_NGINX=986

RUN \
  dnf install -y epel-release https://yum.osc.edu/ondemand/2.0/ondemand-release-web-2.0-1.noarch.rpm \
  && dnf module enable -y ruby:2.7 nodejs:12 \
  && dnf install -y ondemand \
  \
  && usermod -u $UID_SASLAUNTH saslauth \
  && usermod -u $UID_ONDEMAND_NGINX ondemand-nginx \
  \
  && dnf -y clean all \
  \
  && systemctl enable httpd
  

