FROM izone/hpc:ood-base
MAINTAINER Leonardo Loures <luvres@hotmail.com>

RUN \
  dnf install -y mod_authnz_pam \
  \
  # Config PAM
  && cp /etc/pam.d/sshd /etc/pam.d/ood \
  && chmod 640 /etc/shadow && chgrp apache /etc/shadow \
  && echo "LoadModule authnz_pam_module modules/mod_authnz_pam.so" \
                                        > /etc/httpd/conf.modules.d/55-authnz_pam.conf \
  \
  && dnf -y clean all \
  \
  && systemctl enable httpd
